server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:petrelevich/jvm-digging.git"
          search-paths: "spring-cloud/git-config"
          ignoreLocalSshSettings: false
          strictHostKeyChecking: false
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - metrics
          - refresh
    enabled-by-default: false
