spring:
  application:
    name: demo-api-gateway


server:
  port: 7777

application:
  api-routes:
    - id: "service-client"
      from: "client"
      to: "lb://SERVICE-CLIENT"
    - id: "service-order"
      from: "order"
      to: "lb://SERVICE-ORDER"

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1
